/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FineritIcons {
  FineritIcons._();

  static const _kFontFam = 'FineritIcons';

  static const IconData like = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData like_on = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData like2 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData like2_on = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData like3 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData like3_on = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData look = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData medal = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData medal2 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData medal3 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData message = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData message2 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData message3 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData message4 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData mine = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData more = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData newtask = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData pen = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData playlast = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData playnext = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData rank = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData rank1 = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData rank2 = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData ranking1 = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData ranking2 = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData ranking3 = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData ranking4 = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData ranking5 = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData ranking6 = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData ranking7 = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData ranking8 = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData remove = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData right1 = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData safe = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData school = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData send = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData success = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData twosquare = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData unlock = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData up1 = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData video = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData voice = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData wallet2 = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData warning = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData winning_course = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData write = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData write1 = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData write2 = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData addfriend = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData addressbook = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData addressbook2 = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData addsuccess = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData alter = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData alteruser = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData article = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData article2 = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData auth = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData authfalse = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData authsuccess = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData bofang = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData chart = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData cloud = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData comment2 = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData create = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData create2 = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData cup1 = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData cup2 = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData down1 = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData eyeclose = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData eyes = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData fail = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData false_icon = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData favorite = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData feedback = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData frienddelete = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData godcomments = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData house = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData image = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData iphone = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData jianpan = const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData left1 = const IconData(0xe861, fontFamily: _kFontFam);
}
